// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5vJvm_y0EBrAK25LbdIBaXcTdCWtccio',
    appId: '1:183759925017:web:94b6087a0bda4eec9cdf88',
    messagingSenderId: '183759925017',
    projectId: 'parking-app-be29f',
    authDomain: 'parking-app-be29f.firebaseapp.com',
    databaseURL: 'https://parking-app-be29f-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'parking-app-be29f.firebasestorage.app',
    measurementId: 'G-Y4TNC5C9EZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7Nj00BpFWt_OzS8Jvx6x9nvKaaN3tEYA',
    appId: '1:183759925017:android:5a954cf3284271f39cdf88',
    messagingSenderId: '183759925017',
    projectId: 'parking-app-be29f',
    databaseURL: 'https://parking-app-be29f-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'parking-app-be29f.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA5vJvm_y0EBrAK25LbdIBaXcTdCWtccio',
    appId: '1:183759925017:web:8c413e49dc2e4f139cdf88',
    messagingSenderId: '183759925017',
    projectId: 'parking-app-be29f',
    authDomain: 'parking-app-be29f.firebaseapp.com',
    databaseURL: 'https://parking-app-be29f-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'parking-app-be29f.firebasestorage.app',
    measurementId: 'G-XWFP0BQPTV',
  );
}
